name: Docker CI/CD

on:
  push:
    branches: [ "main" ]        # main ga push bo'lsa deploy bo'ladi

jobs:
  build_and_push:
    runs-on: ubuntu-latest
    steps:
      - name: Repository code-ni olish
        uses: actions/checkout@v3

      - name: Docker Hub ga login
        run: echo "${{ secrets.DOCKERHUB_PASSWORD }}" | docker login -u "${{ secrets.DOCKERHUB_USERNAME }}" --password-stdin

      - name: Docker image build qilish
        run: docker build -t ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APP_NAME }}:latest .

      - name: Docker Hub ga push
        run: docker push ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APP_NAME }}:latest

  deploy_to_server:
    needs: build_and_push
    runs-on: ubuntu-latest
    steps:
      - name: Serverga SSH orqali ulanib container yangilash
        uses: appleboy/ssh-action@v0.1.10
        with:
          host: ${{ secrets.SERVER_HOST }}      # IP
          username: ${{ secrets.SERVER_USER }}  # root
          key: ${{ secrets.SERVER_KEY }}        # id_rsa (private key)
          script: |
            docker pull ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APP_NAME }}:latest
            docker stop ${{ secrets.APP_NAME }} || true
            docker rm ${{ secrets.APP_NAME }} || true
            docker run -d --name ${{ secrets.APP_NAME }} -p 3000:3000 ${{ secrets.DOCKERHUB_USERNAME }}/${{ secrets.APP_NAME }}:latest
            echo "ðŸš€  CI/CD deploy tugadi! 3000-port orqali ishlayapti!"
